language: java

jdk:
  - oraclejdk11

sudo: false
env:
    global:
        #key for github
        #GITHUB_OAUTH_TOKEN
        - secure: "KsniGjagnl/YYIFmOdQ0mkCBewoCbNkOLiHSERANJ2+b+/ccwchEci1ArfZDJxBKH+3zoCg3bozWjyc7P5fPSOTSeJQEFeFMLYnucrKuJh/+z0qX7F6Wc1jRTx5tKjd01kH2vGZVHSAxBX5ieNm8MPBoMQOsYLXpnF68wMHGuRMLMeQmXKXB6SNT/i3ILY0wP0Tf4SoGoqOpk12Fhip56+lH8Uba0h9tTiSxRWfNDMUMH66SOukQPml/pzZ49+Q74JW0F1UaowKY3avsh8RahKCY2FVtYmJG0l1VdhGT6Z7uePp+axB8lbd/EyCzVt61Xo5M7+K3SyYLjJ4eHjzPBk2NDeEZBa5gt27VJMkdzLDaNg9C5XBEBXkyTBaeTpT3FBa1TIO6HqKfuaTq24U46NngOqf6KZxxudqOHOKGIEZS0PoTuNfqhiqoouJKfxwVvRW3ES847ZU35gLWYI8f8TDFRyXgZMPx8swMUdErp0FZJafdrVcxcq2K2b3zN9bkLp1fbmk8CbANgYL7ChpqWbM85pooUltB5nmitN+4DqzMylMNoORTZoVGWLOs529dm5vci1jvl+jZEHI1XqxJmXLK9SYyAL6JyLZRr12gsy23bC/9wDFwGu+I+Eqe4gj/0jpSgVVZV2eVb9WubB9EPjI8vXgJhb1v9aHJoNreUD4="
        - environment=test
        #sonatype credentials
        #OSSRH_JIRA_USERNAME
        - secure: "LMQpGCtVJGzpgOqNZZBoAKx0xwZuyInGvKLOgLH4VxJLGWxxxXt5LSgnYxo16G0eTckGk+fFMdBW2k8QhhA9uZOOahzq9/myD0nmc3JLOHmOWJcQrLL50UDQzAiYCP4rToF/Q/RWG5bjkc5eZZ7KSeANL1VYM9yyV4+tNPR7UsxAfbUh1+zkDhBeb0Ot35cw/YgO0jn/RFyTZ44mzyl9mf9hfaIk42+urdBfOSkv9XarGjB4WtAYnsryAJ5qoPmnpNJGV4MJCMnxQF4f0U+4fTVS8sBTMaU6Y/3CqhTRXgFoGblzczau5oZbpoyuHT0zUKL1F6gv+VWWAPoU3oVlG/S+IMJW00jBWvpVOKWISKllx6ESRZ563p505JIlUBcmcb0pn6DZ/4+wYED+pIHYHUXxu77C9Pamhov/ESft9Tm3l+XYoBKeWiJ3l1XH+VzotkMA4fojprOGZ4Qe0+VbgeftKaMjocJm8JMzTeod8mDw/grTq9TL3KHCHYv7QzW3p2ChIMPJdD0/Pq3urx9PjUUAmtlwP6OvdEa6zrU8LA0HpRmimgt19PF7go+9thLHzwgMGLGImlRNEzWXIEgbuX/8dewhD217/t+w/DDytzkknttfdwZT9cgNLHL7ymyllE7ISu3PwfuHYQdRPcxLtzbxLrN3h9x8qiP7WCN6D5w="
        #OSSRH_JIRA_PASSWORD
        - secure: "ct0Qy/64atkMVN91Ojhvmx6CY3k7l2EWvkp78gzTf1gK7sQnpaLUcLVQ7XSZqlqrdS7qS8QktwPvhuupj73KXDzM25E6iEQ4xGSmYP3+/0kNkGB0wKErocTchHL5bIrasX47mI6IxzzHxjYcQpaFLkmcwd74PTctS2HVx3mjFA0cZZekg0MLQMGQ8ckaUEkFXQSryF+hEwodkbvcLQ2nAkWoB7eOKfllqkeoGLBLdWnSuUED3mm9ubpKLfRW73SP9fQ8DznTkxEOLZ4j0UphA+OKMS+xqWm/dYoN+nhDsoRt5vzXm3CIVRAXtvOHn+54tAaQsDiYdAeKWjUWOGhPmcPIewx2r9ZZ7epI9fpRYo9Q6BFGZmvWgR3F66tfWKT37tfjZ7Y8+65iGcEziNgBkatd8SHX8udy0/IO5IwxORaY7U6PDEZPhIRGUXAqAcK8TSm3pm85k9yl962Pq1oK/3aqi5mXKFVMYOz4uGLv2skCFq6HEftp+tI/OeLX4rAB2mLpYrxSlmvuBqmEpyAZKGvoKYpk+PJkbne1QGafXV/Ffu5IoOGH9eMqAa/a299lXMwNVod484gTyMYhFebH8sL8VEBheAVPqZwRUD2CVv+gC0mOPkKbrR242zsNakktD/dFV4+9WRyrBzvaZ9K4I3iZO0Y0YRW7yAQu7gOqDWs="
        #signing key
        #GPG_KEY_NAME
        - secure: "KkMvDt0+ysThWvos8NwqZe77EltC6M0Ukn4q/lvR7Ad/PZnYtU6z8J7K+GOFkDWs1PIKaO6uKkYCTF7Y61Ky89ZQ6tVrBVOt3NeQSUlxIsPNsEQaYChYUxFJdh+qjUEgXXzsjgN07gq5UhjufmAHL90jIKZ4QdVdyuqMVGrwobaJ2bVK1VwaCjFwk3tKPUkS7h5nZR2h3JHcdOcr4VpY7GhvWwE5ki9bDxuKo4QxXNL36EQzbpeERSHWsIuR1UKtbZA2HG8ZIUgZ8xNNvnzPK0GUu7rArsy8ixGk6XTSRNZBfsR6qUZt+NCfLmilUtL2rNW/OkupBwK2B8xH2txf0shQmurskWx7qZOXEpAIfeecvUovfNbsPqAe4f2av3F+sy0NUw7zf2N76xUh6VKT6CFFlFCITyv443NOrAfACl9KWp4Gk6Z1wcG/KylEzY+ri13X7VPLIvxsPGGL7jtksLOzPCcmuV+IKfA1nlU0pB2xzbjbJ1WRdn8LSd+JmLS831PFzqOnN7oB2Isp7k5nXZjFgSl6YK37cbGHSSASWe6TYqcoG5P8+mTuM/0zWzHeJdHTvDuDJs98FuxN9xz0h5wkG3Nt1YOOAflEo5/fxTclmuDEkoBGJnNLkatHAuTDcKky3Fs3B2AySgZ+yWhEjRrEh3eMo+4hNt+saibE3bw="
        #GPG_PASSPHRASE
        - secure: "MVerYRETXWWbuXeYAWcrNf7xNWCm4mrMt9WQCRWk9LQK2acLvvnAcQH5fOPKDU9ll9AolMBXxUvHiZIrxqLEGqTgd2tEQ+Iz5t7q14Gvcqo7Z3Dk8HspoZXNATqsK6TVWsvV17CJ/HMLxtktPlRgVUrgWZRF65i/0E/xbTxo5YhMAqJkEVai16snQ1fUsc4SnsBrEds0pz5y//ksaQMeClqe47CbzrnSqZC2Bj/FvvLptpUwOAksjzkJbQcKxsS5DHUzX8xsG76C/Odpqi6IeB2vPoHsGYcyRmmN/ZPgj5hDIsR8QkSbK4CnL5o3UcUTChf01r10EXVs+R7ULhmhaDhsjrTJnjvAu8gjCr+cdH/7bzNJzGJX5dMPf+/NDo4uqRQLZKrRif8bOr02jOIK8j/CCQtH389mTzgxrcfULmoiHrIRFGamrgmi19y0lu7ODuDb92GJmjEfzdBZGG4TtZ1svg4npmCslOjoA9zbPbXi9o2t050U2rjG/iHCNaEF4ETjOfSYIXpXi5mAJes3eSpxisXxLCmbVkx7/vySXei6LQI2ewkWDmhJEEgMxie0TKCUonnCbS2ppLKfNfXWBJD86f94gCItwaOGL130orIVG5cX8XMFVHTuq+mWNxlsXKVCIJ1FWcejl6fNpjVpT98XnVzWu9FT2SLb3JOsX4E="

addons:
  sonarcloud:
    organization: "albertoirurueta-github"
    token:
      secure: "M3JoyhUK0YHoO4N/i5tMZWHMs91lVnldAxtRTE3rJfvJS2M2REZ2MaDVoJXjvAC6NHoEN8J4uB1xeNtqy1l6rUhn3LC+2lfZ1RXDhVWWvrQeN1cRdDVSvd44afvNwn6eqo5RNM6Grvy0oX7O3bK60xUifMRi2Rdrkpl0gdfkd0j9a/+SnXJ4ULbuaKAjjHRmRgDAYrzpKEOQNyxytpvUVbRfJYhVvmgcVaUdL1bwwLXuplSoiwVq4QAWpsr70wNixpRCNkaBiPTazloYHdNxAEwjWw4qsTnAR3n9UeOThOzqhpMZhLCwZUxaC7RxuyrHd4W3EVLAePplhEB6fBaRNSi08AUKUWByYDHOuN9akAhH00EwtkuAGPoTMgR3ts2K4/4/03VSoR8Xo6cIc4ss0OjfHVFcYpvaT+oFz5UUowA0ewRY9y/e4RnGrUrdufTqcCQQveUHGlBsfCWbSluLFvOSBxX8FWcrKPqe0pr69CEeKzSOu6iAEsVcdhcnb4U5/CN62XHLdFC0+ZxvTMmLVnwv5jlzFuXzaaWztgLPkKIufI1Ga+p8WSRxY20SkiKY20TWqjLv8TrJ5LyZ1U89D44LrNfPFVENve0rb7yJzPjPm9jtNN38MmNwLpIwqdfWZFd0TO7enUqEsT7BDxjLsmnrr4EiT5AX6O/wB4GR+g0="

#if timeout occurs, add travis_wait as in example below:
#script: travis_wait mvn clean jacoco:prepare-agent install jacoco:report site

#add: -Denvironment=test to activate CI profile to publish into gh-pages
script:
  - ./cd/decode.sh
  - travis_wait mvn clean jacoco:prepare-agent install jacoco:report -Denvironment=test -P !build-extras
  - mvn site -Djacoco.skip -DskipTests -P !build-extras
  - sonar-scanner

cache:
  directories:
    - ~/.m2/repository

deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_OAUTH_TOKEN
  keep-history: true
  local-dir: ./target/site
  on:
    branch: master

after_success:
  - ./cd/before-deploy.sh
  - ./cd/deploy.sh
